name: .NET

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore MapApp
      
    - name: Build WebAPI
      run: dotnet build MapApp/WebAPI/WebAPI.csproj --configuration Debug --no-restore
     
    - name: Build ConsoleApp
      run: dotnet build MapApp/ConsoleApp/ConsoleApp.csproj --configuration Debug --no-restore
      
    - name: Build EncouterMeTests
      run: dotnet build MapApp/EncounterMeTests/EncounterMeTests.csproj --configuration Debug --no-restore
    
    - name: Test
      run: dotnet test MapApp/EncounterMeTests --no-build --verbosity normal
