name: Build Xamarin.Android app

on: 
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set default Xamarin SDK versions
      run: |
        $VM_ASSETS/select-xamarin-sdk-v2.sh
    - name: Setup .NET Core SDK 5.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Install dependencies
      run: nuget restore MapApp/MapApp.sln

    - name: Build
      run: msbuild MapApp/MapApp/MapApp.Android/MapApp.Android.csproj /t:Rebuild /p:Configuration=Debug
